#cloud-config
users:
  - name: yc-user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDRqmrg7m8kvN1ql81intN0bn4UZ2bohZ2bhOHp5A4yxOmuDvmfhFzTvNVwDDZfQsR0Dt3JSuEEEFARwAnVU8MUKT3VTRTcF2nfxRJCyJXb96fng4qDZpq0Cj/GNuaWyIyC8CpTBeTySVQiOpTAIZEoppsPw/VkjxcOCu6QbNArCc8BDHeLKvv9hPbbG8p2y2eis/Eki45cgkpKsWwrzZC69t+dfNngZ9oJsExiDa5EAhL5tMxnCfi9CNE6rZr21pcM1oZR6jmkvhGrbKj51xRGW0VA80aSN6GiLWMMaVCjYFzu5alG83fasN3m+eqDVjDuzIUnvQL7ptdn1kaPjHxJ71j7HlXMUbxL5gqlh+RKD2pqGA0G6omoReBW+SJZkjRDtKOeiMwapyQKxV/UCCNUyxtwSpGPJ5TSF8QwyuXv/r/K21xJ2eCb4nQl64d3DwIkMtv8JbW0uPk05Lnw5W7ulXoslo+sFqw6W0rY+Sp5bBuh3xuLwT2KSfUE19dfP2s= appuser

runcmd:
  - 'apt-get update'
  - 'apt-get install -y ruby-full ruby-bundler build-essential mongodb git'
  - 'echo `ruby -v` && echo `bundler -v`'
  - 'systemctl status mongod | grep active'
  - 'git clone -b monolith https://github.com/express42/reddit.git'
  - 'cd reddit && bundle install && puma -d'
